### ISSUE TITLE
The addon does not work for me

### ISSUE THREAD

**Issue by Maverick1435** [ahmedthebest31/navsounds#14]
Hello. I am having trouble getting  the addon to work. When I install it, nothing happens. I've tried looking in the navigation settings and used different sounds, and still nothing. I am using NVDA version 2020.4 which is a compatible version for the addon, so I believe that shouldn't be an issue. I  also noticed that the addon does not create a shortcut to turn the sounds on and off. Any help to fix this issue would be greatly appreciated. Thanks in advanced

**Comment by ahmedthebest31** [comment]
Actually
I don't know what's causing the problem

I'm actually using the same version you're using now

If you get an error message, tell me about it. This will be a good helper to find out what the problem is and how to solve it

First, we can try solutions for general problems that occur with all add-ons

Such as:

Delete it completely, restart nvda, then install it again

Try to download it from github this time instead of the add-on store

Because the nvda addon store has many problems currently and this may be the reason for the problem

Try these solutions and let me know the what's happend.

**Comment by Maverick1435** [comment]
I've tried all that you have mentioned, but I still was not able to get it to work. I have pulled this though from my NVDA log, if that helps. ERROR - globalPluginHandler.initialize (08:24:28.478) - MainThread (18224):
Error initializing global plugin <class 'globalPlugins.NavigationSounds.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 33, in initialize
  File "C:\Users\MyUser\AppData\Roaming\nvda\addons\navSounds\globalPlugins\NavigationSounds\__init__.py", line 89, in __init__
    old = speech.speech.getPropertiesSpeech
AttributeError: module 'speech' has no attribute 'speech'

**Comment by ahmedthebest31** [comment]
I realised the problem and I fix it 
please remove the addon completely  restart nvda and reinstall it againe 
and everything will be fine. 
if the issue  still happening with you try to install it from github instead not the nvda store
